// shared/types/user.d.ts
import { Request } from 'express';
import { ObjectId } from 'mongodb';

/**
 * Represents a badge earned by a user.
 * - `type`: The type of badge (e.g., 'community', 'milestone', 'leaderboard')
 * - `name`: The name of the badge (e.g., 'Community Member', '50 Questions', 'Top 10')
 * - `earnedAt`: The date when the badge was earned
 */
export interface Badge {
  type: string;
  name: string;
  earnedAt: Date;
}

/**
 * Represents user credentials for authentication.
 * - `username`: The unique username of the user.
 * - `password`: The user's password.
 */

export interface UserLogin {
  username: string;
  password: string;
}

export interface UserSignup {
  firstName: string;
  lastName: string;
  username: string;
  password: string;
}

/**
 * Represents a user document, including user credentials and additional details.
 * - `username`: The unique username of the user.
 * - `password`: The user's password.
 * - `dateJoined`: The date when the user registered.
 * - `biography`: A short description or bio of the user (optional).
 * - `isOnline`: A boolean value indicating if the user is currently connected to the platform.
 * - `socketId`: The Socket.IO connection ID for real-time communication (null when offline).
 * - `lastSeen`: The timestamp of when the user was last active or disconnected.
 * - `badges`: An array of badges earned by the user.
 * - `hasSeenWelcomeMessage`: A boolean indicating if the user has seen the welcome message.
 * - `points`: The total points accumulated by the user through platform activities.
 * - `major`: The user's major/field of study.
 * - `graduationYear`: The user's expected graduation year.
 * - `showStats`: A boolean indicating if the user has opted to display their statistics publicly.
 * - `externalLinks`: An object containing optional external links (LinkedIn, GitHub, Portfolio).
 * - `coopInterests`: A string describing the user's co-op interests.
 * - `careerGoals`: A string describing the user's career goals.
 * - `technicalInterests`: A string describing the user's technical interests.
 */
export interface User extends UserSignup {
  dateJoined: Date;
  biography?: string;
  isOnline?: boolean;
  socketId?: string | null;
  lastSeen?: Date;
  badges?: Badge[];
  hasSeenWelcomeMessage?: boolean;
  points?: number;
  major?: string;
  graduationYear?: number;
  showStats?: boolean;
  externalLinks?: {
    linkedin?: string;
    github?: string;
    portfolio?: string;
  };
  coopInterests?: string;
  careerGoals?: string;
  technicalInterests?: string;
}

/**
 * Represents a user document in the database.
 * - `username`: The unique username of the user.
 * - `password`: The user's password.
 * - `dateJoined`: The date when the user registered.
 * - `biography`: A short description or bio of the user (optional).
 * - `_id`: The unique identifier for the user, generated by MongoDB.
 */
export interface DatabaseUser extends User {
  _id: ObjectId;
}

/**
 * Express request for user login, containing user credentials.
 * - `username`: The username submitted in the request (body).
 * - `password`: The password submitted in the request (body).
 * - `biography`: Optional field for biography information (body).
 */
export interface SignupRequest extends Request {
  body: {
    username: string;
    password: string;
    firstName: string;
    lastName: string;
    biography?: string;
  };
}

export interface LoginRequest extends Request {
  body: {
    username: string;
    password: string;
  };
}

export interface UserRequest extends Request {
  body: {
    username: string;
    password: string;
    firstName?: string;
    lastName?: string;
    biography?: string;
  };
}

/**
 * Express request for querying a user by their username.
 * - `username`: The username provided as a route parameter.
 */
export interface UserByUsernameRequest extends Request {
  params: {
    username: string;
  };
}

/**
 * Represents a "safe" user object that excludes sensitive information like the password.
 */
export type SafeDatabaseUser = Omit<DatabaseUser, 'password'>;

/**
 * Represents the response for user-related operations.
 * - `SafeDatabaseUser`: A user object without sensitive data if the operation is successful.
 * - `error`: An error message if the operation fails.
 */
export type UserResponse = SafeDatabaseUser | { error: string };

/**
 * Represents the response for multiple user-related operations.
 * - `SafeDatabaseUser[]`: A list of user objects without sensitive data if the operation is successful.
 * - `error`: An error message if the operation fails.
 */
export type UsersResponse = SafeDatabaseUser[] | { error: string };

/**
 * Express request for updating a user's biography.
 * - `username`: The username whose biography is being updated (body).
 * - `biography`: The new biography content to be set (body).
 */
export interface UpdateBiographyRequest extends Request {
  body: {
    username: string;
    biography: string;
  };
}

/**
 * Represents the authentication response containing the user and JWT token.
 * - `user`: The authenticated user object without sensitive data.
 * - `token`: The token for session management includes userId and username.
 */
export type AuthResponse = {
  user: SafeDatabaseUser;
  token: string;
};
